### PR TITLE
Added Spectral Timer

### PR DESCRIPTION
**Pull request by spide-r**
Spectral Timer + New Setting to only show the overlay header.

### CODE REVIEW

**Comment by NotNite** [comment]
/remindme 1h30m
image

**Comment by spide-r** [comment]
Resolved issue w/ spec timer in first zone + made sure that the spectral timer never exceeded the actual time remaining in the instance (factoring in the hard-stop at 30s).

**Comment by spide-r** [comment]
no spec -> late spec -> spec caused timer to go in the negatives

reviewing

**Comment by Nukoooo** [comment]
While you are at it, wouldn't it better to hook the update thingy function for InstanceContentOceanFishing? Possibly refactoring other code with this function, since the game handles most of the ocean fishing related in this function, tho updating caught fish is done in a network packet.

https://github.com/Nukoooo/Dalamud.FishersIntuition/blob/5013c9bae0b8f747f4546eb61a6a7ebbe84b2612/FishersIntuition/Timers/WeatherTimer.cs#L40-L44 (my code works in most cases, but when a spectral happens when the current zone has only about one and a half minutes left, the timer in the next zone will have 10+ seconds more than the actual timer)

Edit: SetSpawnPlaceName type is wrong btw, I have no idea what it is. I tried to figure out if it is accessed by anything but it seems like nothing actually accesses the fields that type 10 updates

**Comment by NotNite** [comment]
Should this be marked as a draft or is it ready to merge?

**Comment by spide-r** [comment]
I want to say ready to merge but I want to test it one final time at the 10pm GMT boat.

**Comment by spide-r** [comment]
@NotNite ready to merge

**Pull request merged**
